version: '3.9'
services:
  web:
    build: ./django
      # context: .
      # dockerfile: Dockerfile
    image: weare-dev
    restart: unless-stopped
    user: 1000:1000
    # command: python -m uvicorn config.asgi:application --reload --host web --port 8000
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn config.wsgi:application --workers 4 --bind 0.0.0.0:8000 --log-level DEBUG
    env_file:
      - ./django/.env
    ports:
      - "8008:8000"
    container_name: weare_dev
    volumes:
      - ./django:/code:rw
      - ./django/cache:/code/cache:rw
    depends_on:
      - db

  db:
   image: postgres:16-alpine
   container_name: weare_db
   restart: unless-stopped
   volumes:
     - weare_pg_data:/var/lib/postgresql/data/
   env_file:
     - ./db/.db.env


volumes:
  weare_pg_data:
#networks:
#  djangonet:
 
