# Generated by Django 5.0.2 on 2024-04-10 11:11

import blog.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('main_image', models.ImageField(upload_to=blog.models.upload_directory_path, verbose_name='Главное изображение')),
                ('text', models.TextField(blank=True, max_length=8000, null=True, verbose_name='Основной текст')),
                ('photo_date', models.DateField(verbose_name='Дата фотосъемки')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('views', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров')),
                ('images_ordering', models.CharField(choices=[('file', 'Filename'), ('name', 'Name'), ('index_number', 'Index')], default='file', max_length=30)),
                ('videos_ordering', models.CharField(choices=[('file', 'Filename'), ('name', 'Name'), ('index_number', 'Index')], default='file', max_length=30)),
                ('average_stars', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True, verbose_name='Average Stars')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(help_text='Выберите категорию', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='post', to='blog.tag', verbose_name='Метки')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index_number', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядковый номер')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('file', models.ImageField(max_length=250, upload_to=blog.models.image_directory)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('exif_data', models.JSONField(blank=True, default=dict, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('audio', models.FileField(upload_to=blog.models.video_directory)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audios', to='blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, null=True, verbose_name='Stars')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('index_number', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядковый номер')),
                ('file', models.FileField(upload_to=blog.models.video_directory)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=blog.models.video_directory)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('thumb_select', models.CharField(choices=[('--start.jpg', 'start'), ('--mid.jpg', 'mid'), ('--end.jpg', 'end')], default='--start.jpg', max_length=15)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='blog.post')),
            ],
        ),
    ]
