# Generated by Django 5.0.2 on 2024-04-10 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_image_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='images_ordering',
            field=models.CharField(choices=[('file', 'Filename'), ('index_number', 'Index'), ('name', 'Name')], default='file', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='videos_ordering',
            field=models.CharField(choices=[('file', 'Filename'), ('index_number', 'Index'), ('name', 'Name')], default='file', max_length=30),
        ),
    ]
