# Generated by Django 5.0.2 on 2024-04-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_images_ordering_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='author',
        ),
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
    ]
